apiVersion: batch/v1
kind: Job
metadata:
  name: {{.jobName}}-{{.Iteration}}
  namespace: {{.namespace}}
  labels:
    app: kata-io
    benchmark: io
    preload: images
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: kata-io
        benchmark: io
        preload: images
    spec:
      restartPolicy: Never
      nodeSelector:
        perf.azure.com/node-role: workload
      containers:
        - name: preload
          image: {{.benchmarkImage}}
          imagePullPolicy: IfNotPresent
          command: [override, command]
