apiVersion: v1
kind: Pod
metadata:
  name: {{.jobName}}-{{.Iteration}}
  namespace: {{.namespace}}
  labels:
    app: kata-io
    benchmark: io
    preload: images
spec:
  restartPolicy: Never
  nodeSelector:
    perf.azure.com/node-role: {{.nodeRole}}
  containers:
    - name: preload
      image: {{.benchmarkImage}}
      imagePullPolicy: IfNotPresent
      command: [override, command]
