apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.jobName}}-work-{{.Iteration}}
  namespace: {{.namespace}}
  labels:
    app: kata-io
    benchmark: io
    pvc-role: work
    storage-type: {{.storageType}}
spec:
  accessModes:
    - {{.workAccessMode}}
  storageClassName: {{.workStorageClass}}
  resources:
    requests:
      storage: {{.workVolumeSize}}
