apiVersion: v1
kind: Pod
metadata:
  name: kata-perf-{{.Iteration}}-{{.Replica}}
  labels:
    app: kata-perf
spec:
  runtimeClassName: kata-vm-isolation
  nodeSelector:
    perf.azure.com/node-role: workload
    kubernetes.azure.com/os-sku: AzureLinux
  restartPolicy: Never
  containers:
    - name: pause
      image: {{.image}}
      imagePullPolicy: IfNotPresent
