apiVersion: v1
kind: Pod
metadata:
  name: storage-kata-pvc-{{.Iteration}}-{{.Replica}}
  labels:
    app: kata-perf-storage
spec:
  automountServiceAccountToken: false
  runtimeClassName: kata-vm-isolation
  nodeSelector:
    perf.azure.com/node-role: workload
    kubernetes.azure.com/os-sku: AzureLinux
  restartPolicy: Never
  containers:
    - name: pause
      image: {{.image}}
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: storage
          mountPath: /storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: storage-{{.Iteration}}-{{.Replica}}
