apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-{{.Iteration}}-{{.Replica}}
  labels:
    app: kata-perf-storage
spec:
  accessModes:
    - {{.accessMode}}
  storageClassName: {{.storageClass}}
  resources:
    requests:
      storage: 1Gi
