jobs:
- name: kio-clean-jobs
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  qps: 20
  burst: 20
  objects:
  - kind: Job
    apiVersion: batch/v1
    labelSelector:
      app: kata-io
      benchmark: io
- name: kio-clean-work-pvcs
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  qps: 20
  burst: 20
  objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    labelSelector:
      app: kata-io
      benchmark: io
      pvc-role: work
- name: kio-clean-pods
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  qps: 20
  burst: 20
  objects:
  - kind: Pod
    apiVersion: v1
    labelSelector:
      app: kata-io
      benchmark: io
