global:
  measurements:
    - name: podLatency
jobs:
  - name: kio-namespace
    jobType: create
    namespace: default
    jobIterations: 1
    qps: 1
    burst: 1
    cleanup: false
    waitWhenFinished: true
    objects:
      - objectTemplate: templates/namespace.yml
        replicas: 1
        inputVars: {}
  - name: kio-results-pvc
    jobType: create
    namespace: kata-io
    jobIterations: 1
    qps: 1
    burst: 1
    cleanup: false
    waitWhenFinished: true
    objects:
      - objectTemplate: templates/results-pvc.yml
        replicas: 1
        inputVars: {}
  - name: kio-smoke-1
    jobType: create
    namespace: kata-io
    jobIterations: 1
    qps: 1
    burst: 1
    cleanup: true
    waitWhenFinished: true
    preLoadImages: true
    objects:
      - objectTemplate: templates/fio-emptydir-standard-job.yml
        replicas: 1
        inputVars:
          jobName: standard-emptydir-fio-randread
          scenario: runtime-standard-storage-emptydir-fio-randread-4k-concurrency-1
          runtime: runtime-standard
          storageType: storage-emptydir
          workloadType: fio
          fioProfile: /profiles/randread-4k.fio
          fioProfileName: randread-4k
          concurrency: "1"
  - name: kio-smoke-2
    jobType: create
    namespace: kata-io
    jobIterations: 1
    qps: 1
    burst: 1
    cleanup: true
    waitWhenFinished: true
    preLoadImages: true
    objects:
      - objectTemplate: templates/fio-emptydir-kata-job.yml
        replicas: 1
        inputVars:
          jobName: kata-emptydir-fio-randread
          scenario: runtime-kata-storage-emptydir-fio-randread-4k-concurrency-1
          runtime: runtime-kata
          storageType: storage-emptydir
          workloadType: fio
          fioProfile: /profiles/randread-4k.fio
          fioProfileName: randread-4k
          concurrency: "1"
  - name: kio-smoke-3
    jobType: create
    namespace: kata-io
    jobIterations: 1
    qps: 1
    burst: 1
    cleanup: true
    waitWhenFinished: true
    preLoadImages: true
    objects:
      - objectTemplate: templates/git-emptydir-standard-job.yml
        replicas: 1
        inputVars:
          jobName: standard-emptydir-git-blobless
          scenario: runtime-standard-storage-emptydir-git-blobless-concurrency-1
          runtime: runtime-standard
          storageType: storage-emptydir
          workloadType: git
          cloneMode: blobless
          concurrency: "1"
  - name: kio-smoke-4
    jobType: create
    namespace: kata-io
    jobIterations: 1
    qps: 1
    burst: 1
    cleanup: true
    waitWhenFinished: true
    preLoadImages: true
    objects:
      - objectTemplate: templates/git-emptydir-kata-job.yml
        replicas: 1
        inputVars:
          jobName: kata-emptydir-git-blobless
          scenario: runtime-kata-storage-emptydir-git-blobless-concurrency-1
          runtime: runtime-kata
          storageType: storage-emptydir
          workloadType: git
          cloneMode: blobless
          concurrency: "1"
