{{- $cloneModes := list (dict "name" "full" "short" "full") (dict "name" "blobless" "short" "bl") -}}
{{- $concurrencies := list 1 10 -}}
{{- $runtimes := list (dict "name" "standard" "short" "std") (dict "name" "kata" "short" "kata") -}}
{{- $storages := list (dict "name" "emptydir" "short" "ed" "template" "emptydir") (dict "name" "azure-disk" "short" "disk" "template" "pvc") -}}
jobs:
- name: kio-clean-jobs
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  preLoadImages: false
  qps: 20
  burst: 20
  objects:
  - kind: Job
    apiVersion: batch/v1
    labelSelector:
      app: kata-io
      benchmark: io
- name: kio-clean-pods
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  preLoadImages: false
  qps: 20
  burst: 20
  objects:
  - kind: Pod
    apiVersion: v1
    labelSelector:
      app: kata-io
      benchmark: io
- name: kio-clean-work-pvcs
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  preLoadImages: false
  qps: 20
  burst: 20
  objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    labelSelector:
      app: kata-io
      benchmark: io
      pvc-role: work
- name: kio-preload-images
  jobType: create
  namespace: kata-io
  namespacedIterations: false
  jobIterations: 1
  qps: 1
  burst: 1
  cleanup: true
  waitWhenFinished: true
  maxWaitTimeout: 10m
  preLoadImages: true
  skipIndexing: true
  objects:
  - objectTemplate: templates/preload-pod.yml
    replicas: 1
    inputVars:
      jobName: '{{.k8sRunID}}-preload-workload'
  - objectTemplate: templates/preload-patch-pod.yml
    replicas: 1
    inputVars:
      jobName: '{{.k8sRunID}}-preload-patchpool'
{{ range $runtime := $runtimes -}}
{{ range $storage := $storages -}}
{{ range $concurrency := $concurrencies -}}
{{ range $cloneMode := $cloneModes }}
- name: kio-{{ $runtime.short }}-{{ $storage.short }}-git-{{ $cloneMode.short }}-{{ $concurrency }}
  jobType: create
  namespace: kata-io
  namespacedIterations: false
  jobIterations: {{ $concurrency }}
  qps: {{ $concurrency }}
  burst: {{ $concurrency }}
  cleanup: true
  waitWhenFinished: true
  preLoadImages: false
  objects:
{{- if eq $storage.name "azure-disk" }}
  - objectTemplate: templates/work-pvc.yml
    replicas: 1
    inputVars:
      jobName: '{{ $.k8sRunID }}-{{ $runtime.short }}-{{ $storage.short }}-{{ $cloneMode.short }}-{{ $concurrency }}'
      storageType: storage-{{ $storage.name }}
      workStorageClass: managed-csi
      workAccessMode: ReadWriteOnce
{{- end }}
  - objectTemplate: templates/git-{{ $storage.template }}-{{ $runtime.name }}-job.yml
    replicas: 1
    inputVars:
      jobName: '{{ $.k8sRunID }}-{{ $runtime.short }}-{{ $storage.short }}-{{ $cloneMode.short }}-{{ $concurrency }}'
      scenario: runtime-{{ $runtime.name }}-storage-{{ $storage.name }}-git-{{ $cloneMode.name }}-concurrency-{{ $concurrency }}
      runtime: runtime-{{ $runtime.name }}
      storageType: storage-{{ $storage.name }}
      workloadType: git
      cloneMode: {{ $cloneMode.name }}
      concurrency: '{{ $concurrency }}'
{{ end -}}
{{ end -}}
{{ end -}}
{{ end -}}
{{ range $concurrency := $concurrencies -}}
{{ range $cloneMode := $cloneModes }}
- name: kio-kp-block-git-{{ $cloneMode.short }}-{{ $concurrency }}
  jobType: create
  namespace: kata-io
  namespacedIterations: false
  jobIterations: {{ $concurrency }}
  qps: {{ $concurrency }}
  burst: {{ $concurrency }}
  cleanup: true
  waitWhenFinished: true
  preLoadImages: false
  objects:
  - objectTemplate: templates/work-block-pvc.yml
    replicas: 1
    inputVars:
      jobName: '{{ $.k8sRunID }}-kp-bl-{{ $cloneMode.short }}-{{ $concurrency }}'
      storageType: storage-azure-disk-block
      workStorageClass: managed-csi
  - objectTemplate: templates/git-block-kata-job.yml
    replicas: 1
    inputVars:
      jobName: '{{ $.k8sRunID }}-kp-bl-{{ $cloneMode.short }}-{{ $concurrency }}'
      scenario: runtime-kata-patched-storage-azure-disk-block-git-{{ $cloneMode.name }}-concurrency-{{ $concurrency }}
      runtime: runtime-kata-patched
      storageType: storage-azure-disk-block
      workloadType: git
      cloneMode: {{ $cloneMode.name }}
      concurrency: '{{ $concurrency }}'
{{ end -}}
{{ end -}}
