{{- $runtimes := list (dict "name" "standard" "short" "std") (dict "name" "kata" "short" "kata") -}}
jobs:
- name: kio-clean-jobs
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  preLoadImages: false
  qps: 20
  burst: 20
  objects:
  - kind: Job
    apiVersion: batch/v1
    labelSelector:
      app: kata-io
      benchmark: io
- name: kio-clean-pods
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  preLoadImages: false
  qps: 20
  burst: 20
  objects:
  - kind: Pod
    apiVersion: v1
    labelSelector:
      app: kata-io
      benchmark: io
- name: kio-clean-work-pvcs
  jobType: delete
  namespace: kata-io
  namespacedIterations: false
  skipIndexing: true
  preLoadImages: false
  qps: 20
  burst: 20
  objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    labelSelector:
      app: kata-io
      benchmark: io
      pvc-role: work
- name: kio-preload-images
  jobType: create
  namespace: kata-io
  namespacedIterations: false
  jobIterations: 1
  qps: 1
  burst: 1
  cleanup: true
  waitWhenFinished: true
  maxWaitTimeout: 10m
  preLoadImages: true
  skipIndexing: true
  objects:
  - objectTemplate: templates/preload-pod.yml
    replicas: 1
    inputVars:
      jobName: '{{.k8sRunID}}-preload-workload'
  - objectTemplate: templates/preload-patch-pod.yml
    replicas: 1
    inputVars:
      jobName: '{{.k8sRunID}}-preload-patchpool'
{{ range $runtime := $runtimes }}
- name: kio-fast-git-{{ $runtime.name }}
  jobType: create
  namespace: kata-io
  namespacedIterations: false
  jobIterations: 1
  qps: 1
  burst: 1
  cleanup: true
  waitWhenFinished: true
  preLoadImages: false
  objects:
  - objectTemplate: templates/git-emptydir-{{ $runtime.name }}-job.yml
    replicas: 1
    inputVars:
      jobName: '{{ $.k8sRunID }}-{{ $runtime.short }}-ed-git-bl'
      scenario: runtime-{{ $runtime.name }}-storage-emptydir-git-blobless-concurrency-1
      runtime: runtime-{{ $runtime.name }}
      storageType: storage-emptydir
      workloadType: git
      cloneMode: blobless
      concurrency: '1'
{{ end -}}
